# -*- coding: utf-8 -*-

# Macro Begin: /home/spot/.local/share/FreeCAD/Macro/NewDrawFromBodyOrFunction.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCADGui as Gui
import FreeCAD    as App
import sys
mod_to_import = 'MyTools'
if mod_to_import in sys.modules:
    del sys.modules[mod_to_import]
import MyTools

# Get the list of selected objects
selected_objects = Gui.Selection.getSelection()

# Make new draw
doc, new_page = MyTools.new_techdraw_page()

# Add ProjGroup to the created page
last_ProjGroup     = MyTools.get_highest_ProjGroup_number(doc)
new_ProjGroup_numb = last_ProjGroup + 1
new_ProjGroup_name = f"ProjGroup{new_ProjGroup_numb:03}"
new_ProjGroup      = doc.addObject('TechDraw::DrawProjGroup',new_ProjGroup_name)

# Select only Body
sel_objs    = []
body_parent = None
for sel_obj in selected_objects:
    if sel_obj.TypeId != 'TechDraw::Body':
        body_parent = MyTools.find_body_parent(sel_obj)
        body_parent = body_parent if body_parent else sel_obj
    else:
        body_parent = sel_obj
    sel_objs.append(body_parent)

selected_objects     = sel_objs
new_ProjGroup.Source = selected_objects

# Set the scale
scale_type = 1 # Automatic
pref_scale = MyTools.get_prefered_scale()
new_scale  = None
if pref_scale and pref_scale != 'Automatique' and pref_scale != '':
    scale_type = 2 # Custom
    new_scale  = MyTools.fraction_to_decimal(pref_scale)

# Add ProjGroup
new_page.addView(new_ProjGroup)

# Update scale
new_ProjGroup.ScaleType = scale_type
new_ProjGroup.Scale     = new_scale if new_scale else new_ProjGroup.Scale

# Add first projection 
new_ProjGroup.addProjection('Front')
new_ProjGroup.Anchor.Direction = App.Vector(0.000,0.000,1.000)
new_ProjGroup.Anchor.RotationVector = App.Vector(1.000,0.000,0.000)
new_ProjGroup.Anchor.XDirection = App.Vector(1.000,0.000,0.000)
new_ProjGroup.Anchor.recompute()
doc.recompute()

# Add extra projections to ProjGroup
new_ProjGroup.addProjection('Left')
# new_ProjGroup.addProjection('FrontBottomLeft')
# new_ProjGroup.addProjection('Bottom')
# new_ProjGroup.addProjection('FrontBottomRight')
# new_ProjGroup.addProjection('Right')
# new_ProjGroup.addProjection('FrontTopRight')
new_ProjGroup.addProjection('Top')
# new_ProjGroup.addProjection('FrontTopLeft')
Gui.ActiveDocument.resetEdit()

# Name the draw
MyTools.name_draw(new_page, [new_ProjGroup.Views[0]])

# Set cartridge's scale
MyTools.set_draw_cartridge_scale(new_page, new_ProjGroup)


# Macro End: /home/spot/.local/share/FreeCAD/Macro/NewDrawFromBodyOrFunction.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
